### ISSUE TITLE
v0.16.0+1 Build error - bad state: No element

### ISSUE THREAD

**Issue by terrywarwar** [dart-lang/polymer-dart#33]
I have a working polymer project and get the error message below when I first start the project, or add child polymer elements.

Child Elements are using new @HtmlImport('home_view.html') annotation.

To fix it, I take out the imports statements, which builds successfully.  Then insert the import statements for the children elements and app runs successfully.
`import 'package:app/home_view.dart';
import 'package:app/contact_view.dart';`

Error:
`Transform polymer (PolymerBootstrapTransformer) on app|web/index.html threw error: Bad state: No element
dart:collection/list.dart 133                                            Object&ListMixin.firstWhere
package:initialize/transformer.dart 452:30                               InitializerData.annotationNode
package:web_components/build/html_import_annotation_recorder.dart 30:52  HtmlImportAnnotationRecorder.shouldApply
package:initialize/transformer.dart 279:60                               _BootstrapFileBuilder._buildNewEntryPoint.<fn>
dart:collection/list.dart 127                                            Object&ListMixin.firstWhere
package:initialize/transformer.dart 279:39                               _BootstrapFileBuilder._buildNewEntryPoint
package:initialize/transformer.dart 195:68                               _BootstrapFileBuilder.run
package:initialize/transformer.dart 35:28                                generateBootstrapFile
package:web_components/build/web_components.dart 32:50                   generateWebComponentsBootstrap
package:polymer/src/build/polymer_bootstrap.dart 55:68                   PolymerBootstrapTransformer.apply.<fn>.<fn>
dart:async/zone.dart 1155                                                _RootZone.runUnary
dart:async/future_impl.dart 484                                          _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 567                                          _Future._propagateToListeners
dart:async/future_impl.dart 550                                          _Future._propagateToListeners.handleWhenCompleteCallback.<fn>
dart:async/zone.dart 1155                                                _RootZone.runUnary
dart:async/future_impl.dart 484                                          _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 567                                          _Future._propagateToListeners
dart:async/future_impl.dart 358                                          _Future._completeWithValue
dart:async/future_impl.dart 412                                          _Future._asyncComplete.<fn>
dart:async/schedule_microtask.dart 41                                    _asyncRunCallbackLoop
dart:async/schedule_microtask.dart 48                                    _asyncRunCallback
dart:isolate-patch/isolate_patch.dart 96                                 _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 143                                _RawReceivePortImpl._handleMessage

dart:collection                                                          Object&ListMixin.firstWhere
package:initialize/transformer.dart 452:30                               InitializerData.annotationNode
package:web_components/build/html_import_annotation_recorder.dart 30:52  HtmlImportAnnotationRecorder.shouldApply
package:initialize/transformer.dart 279:60                               _BootstrapFileBuilder._buildNewEntryPoint.<fn>
dart:collection                                                          Object&ListMixin.firstWhere
package:initialize/transformer.dart 279:39                               _BootstrapFileBuilder._buildNewEntryPoint
package:initialize/transformer.dart 195:68                               _BootstrapFileBuilder.run
package:initialize/transformer.dart 35:28                                generateBootstrapFile
package:web_components/build/web_components.dart 32:50                   generateWebComponentsBootstrap
package:polymer/src/build/polymer_bootstrap.dart 55:68                   PolymerBootstrapTransformer.apply.<fn>.<fn>
dart:isolate                                                             _RawReceivePortImpl._handleMessage`

**Comment by jakemac53** [comment]
Got a separate report about this as well, but haven't been able to track it down yet. Do you have any code you can post or a github repo you can link?

**Comment by terrywarwar** [comment]
Here's a github repo that shows the issue,
https://github.com/terrywarwar/core-pages-google-map-example .

main_app.dart has the import statements.

On Fri, Mar 13, 2015 at 8:27 AM, Jacob MacDonald <notifications@github.com>
wrote:

> Got a separate report about this as well, but haven't been able to track
> it down yet. Do you have any code you can post or a github repo you can
> link?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/polymer-dart/issues/33#issuecomment-78626386>
> .
>



-- 
+61 2 8208 8877
+64 3 442 6944

**Comment by jakemac53** [comment]
Thanks, this is a much smaller/better repro than the other one I had. Hopefully we can figure this out pretty soon.

**Comment by jakemac53** [comment]
Interesting, so commenting out `import 'package:google_maps/google_maps.dart';` (and all code that uses it) from `map_view.dart` fixes the issue as well... not sure exactly what to make of that.

**Comment by jakemac53** [comment]
Ok, this should be fixed in https://github.com/dart-lang/initialize/commit/12c867d43519e5324366805cd52a4edfea6fd270. Can you do a pub upgrade (make sure you get initialize 0.5.1+5) and confirm?

**Comment by markhats** [comment]
This has fixed the issue for me.

However, I now get loads of console messages of the following form and my app doesn't run:

```Attributes on switch-control were data bound prior to Polymer upgrading the element. This may result in incorrect binding types. (:1)```

**Comment by jakemac53** [comment]
Any chance you can post a repro of that? One thing that comes to mind, If you are calling initPolymer manually make sure that you aren't creating any polymer elements until after that completes (it now returns a Future<Zone> instead of a Zone).

**Comment by terrywarwar** [comment]
Pub upgrade (initialize 0.5.1+6) fixed the issue.  Thanks.

**Comment by markhats** [comment]
I'm still trying to isolate the above ```...data bound prior to Polymer upgrading the element...``` issue. It seems however, that it is to do with the ordering of ```<link rel="import" href="...">``` statements. Is it now absolutely critical to get these in the right order so that all child elements are included before parent elements, even across files?

**Comment by jakemac53** [comment]
I have a repro on this, it looks like a bug in the transformer. As a workaround for now you can add a dart import from each of  your elements to all the other elements that they are using internally. This ensures that your dependencies are registered first.

**Comment by markhats** [comment]
OK - thanks. I'll give that a try. 

Is that a standard import of the dart file as in:
```import 'my-component.dart';```
rather than the new ```@HtmlImport``` thing?

**Comment by jakemac53** [comment]
Yes, a standard dart import. The issue is with the order in which things get registered if they are only included via a script tag in an html import. By adding the regular dart import it ensures that anything within that import will get registered before the importing library.

**Comment by jakemac53** [comment]
Fwiw, I expect the fix for this to land sometime today so you can just wait if you prefer.

**Comment by jakemac53** [comment]
should be fixed now if you do a pub upgrade (make sure you get 0.5.1+7 of the `initialize`  package)

**Comment by markhats** [comment]
This doesn't seem to have made any difference for me. I still get loads of:
```Attributes on <element-name> were data bound prior to Polymer upgrading the element. This may result in incorrect binding types. (:1)```
errors in my app. 

Switching back to pre 0.16 Polymer is the only way I can seem to get rid of them,

**Comment by jakemac53** [comment]
Actually, I filed a new bug for this https://github.com/dart-lang/polymer-dart/issues/38
